#!/usr/bin/expect
set err 1
set timeout -1
spawn flox develop --refresh --override-input capacitor github:flox/capacitor?rev=$env(GITHUB_SHA)
expect {
   -re  "λ" {
      set err 0
      send "exit\r"
      exp_continue
    }
    eof {exit $err}
}
#TODO run bats test
#send "bats default.bats\r"
#expect {
#   -re "0 failures" {
#    set err 0
#    send "exit\r"
#    exp_continue
#  }
#
#  eof {exit $err}
#}
send "exit\r"
eof {exit $err}
