[devshell]
packages = [
    "nyancat",
    "emacs",
    "hello",
    "cowsay",
    "pre-commit",
    "nodejs",
    "vscode",
    "python3"
]
motd = "{202}Welcome to the Flox Dev Env Project Environment!{reset}\n$(type -p menu &>/dev/null && menu)\n"
name = "flox"

[devshell.startup.venv]
text = '''
if [ ! -d .venv ]; then
    echo "No .venv, running initial setup"
    python -m venv .venv
    source .venv/bin/activate
    pip install -r test_requirements.txt
    pip install -e .[d]
    pre-commit install
else
    source .venv/bin/activate
fi
'''

[[env]]
name = "PROJECT_DIR"
eval = "$PWD"

[[env]]
name = "HOSTNAME"
value = "localhost"

[[commands]]
name = "setup"
command = '''
    pip install -r test_requirements.txt
    pip install -e .[d]
    pre-commit install
'''
help = "re-initialize project"

[[commands]]
name = "lint"
category = "contributing"
command = "pre-commit run -a"
help = "lint the project"

[[commands]]
name = "unit"
category = "contributing"
command = "tox -e py"
help = "run unit tests"

[[commands]]
name = "fuzz"
category = "contributing"
command = "tox -e fuzz"
help = "fuzz the project"
