[programs]
vscode = { extensions = ["ms-python.python", "ms-python.pylint"] }
kubernetes-helm = { version = "3.7" }

bats = {}
curl = { version = "7.7" }
docker = {}
unzip = {}
awscli2 = { version = "2.7.3" }
kubectl = {}

gnugrep = {}
coreutils = {}

[programs.python]
python = "python39"
requirements = '''
    pip
    allure-pytest==2.9.45
    kubernetes
    pytest
'''

[hooks]
postShellHook = '''

#EXAMPLE_VAR="foo"
#echo "Hello World"

echo \# Show versions of packages providing binaries with a bit of color
find @DEVSHELL_DIR@/bin -exec realpath {} \; | \
    cut -d- -f2- | cut -d/ -f1 | sort -u | \
    grep -P --colour=always '(?:^|(?<=[-]))[0-9.]*|$'
echo
'''

