[inputs]
pkgs = {}

[python3Packages.buildPythonPackage]
name = "black"

tools = [
    # "nyancat",
    "hello",
    "cowsay",
    "pre-commit",
    "nodejs",
    "vscode",
    "python3Packages.tox"
]

libraries = [
    # Runtime
    "python3Packages.aiohttp",
    "python3Packages.aiohttp-cors",
    "python3Packages.click",
    "python3Packages.colorama",
    "python3Packages.mypy-extensions",
    "python3Packages.pathspec",
    "python3Packages.platformdirs",
    "python3Packages.tomli",
    "python3Packages.uvloop",
    "python3Packages.typed-ast",
    "python3Packages.typing-extensions",

    # Development
    "python3Packages.coverage",
    "pre-commit",
    "python3Packages.pytest",
    "python3Packages.pytest-xdist",
    "python3Packages.pytest-cov",
    "python3Packages.tox",
]

# =======Environmental Variables=======
#
# You can set env vars for common frameworks like Django, Flask, etc here
PROJECT_DIR = "$HOME/devenv"
HOSTNAME = "localhost"

# ========Shell Commands===============
#
# You may add shell commands that will run in flox develop
postShellHook = '''
echo "Welcome to the Flox Dev Env Project Environment!"
'''
